# Generated by Django 5.0.7 on 2024-07-29 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_artist_is_approved_alter_artist_profile_pic_and_more'),
        ('adminclick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('date_donated', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.donors')),
                ('medium_of_waste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminclick.mediumofwaste')),
            ],
        ),
    ]
