# Generated by Django 5.0.7 on 2024-07-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(null=True, upload_to='pictures/donor'),
        ),
    ]
