# Generated by Django 5.0.7 on 2024-08-07 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_artist_certificate'),
        ('donors', '0003_donation_status_alter_donation_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('expressed_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.artist')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.donation')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.donors')),
            ],
        ),
        migrations.CreateModel(
            name='DonorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.donors')),
                ('interest_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donors.interestrequest')),
            ],
        ),
    ]
