# Generated by Django 5.0.7 on 2024-08-07 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_notification_donation_interest_interestnotification'),
        ('donors', '0004_interestrequest_donornotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestnotification',
            name='interest_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donors.interestrequest'),
        ),
    ]
