# Generated by Django 5.0.7 on 2024-07-29 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_pic',
            field=models.ImageField(default='picture/artist/hi.jpg', null=True, upload_to='picture/artist'),
        ),
        migrations.AlterField(
            model_name='donors',
            name='profile_pic',
            field=models.ImageField(default='picture/donor/hi.jpg', null=True, upload_to='picture/donor'),
        ),
        migrations.CreateModel(
            name='Adminclick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=99999999)),
                ('profile_pic', models.ImageField(null=True, upload_to='picture/admin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
