# Generated by Django 5.0.7 on 2024-07-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_artist_is_approved_alter_artist_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminclick',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='picture/admin/admin.jpg'),
        ),
    ]
