# Generated by Django 5.0.7 on 2024-07-31 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_adminclick_profile_pic'),
        ('adminclick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminclick.mediumofwaste'),
        ),
    ]
