# Generated by Django 5.0.7 on 2024-08-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_artist_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
