# Generated by Django 5.0.7 on 2024-08-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminclick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediumofwaste',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
